### ISSUE TITLE
0.8.11 - Can't launch xcake make

### ISSUE THREAD

**Issue by albyok** [jcampbell05/xcake#186]
I'm sorry, but the new GEM (0.8.11) got a lot of problems. 

The first one 

```
- Reading Cakefile
/Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require': /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/generator/target_file_reference_generator.rb:23: syntax error, unexpected &&, expecting keyword_end (SyntaxError)
        && file_ext != ".xcdatamodeld"
          ^
/Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/generator/target_file_reference_generator.rb:24: syntax error, unexpected &&, expecting keyword_end
        && file_ext != ".xcassets"
          ^
/Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/generator/target_file_reference_generator.rb:25: syntax error, unexpected &&, expecting keyword_end
        && file_ext != ".framework"
          ^
/Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/generator/target_file_reference_generator.rb:26: syntax error, unexpected &&, expecting keyword_end
        && file_ext != ".bundle"
          ^
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/plugin.rb:9:in `block in load_plugins'
	from /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/plugin.rb:9:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/plugin.rb:9:in `load_plugins'
	from /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/dependency_provider.rb:8:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/command/make.rb:22:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/command/make.rb:22:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/bin/xcake:6:in `<top (required)>'
	from /usr/local/bin/xcake:23:in `load'
	from /usr/local/bin/xcake:23:in `<main>'
```

The second one, after I tried to fix  the first one...

```
DEBUG parent_group:FileReference
DEBUG path.basename: Root.strings
/Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/xcode/project.rb:170:in `variant_group_for_path': undefined method `[]' for #<Xcodeproj::Project::Object::PBXFileReference:0x007fc042c971d8> (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/xcode/project.rb:145:in `group_for_file_reference_path'
	from /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/xcode/project.rb:126:in `file_reference_for_path'
	from /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/context/xcodeproj_context.rb:56:in `file_reference_for_path'
	from /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/generator/target_file_reference_generator.rb:47:in `include_file_for_path_and_target'
	from /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/generator/target_file_reference_generator.rb:40:in `block in visit_target'
	from /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/generator/target_file_reference_generator.rb:39:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/generator/target_file_reference_generator.rb:39:in `visit_target'
	from /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/visitor.rb:45:in `visit'
	from /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/dsl/project.rb:83:in `block in accept'
	from /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/dsl/project.rb:82:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/dsl/project.rb:82:in `accept'
	from /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/command/make.rb:25:in `block in run'
	from /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/command/make.rb:23:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/lib/xcake/command/make.rb:23:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/xcake-0.8.11/bin/xcake:6:in `<top (required)>'
	from /usr/local/bin/xcake:23:in `load'
	from /usr/local/bin/xcake:23:in `<main>'
```

**Comment by piv199** [comment]
Yeah, I've the same

**Comment by jcampbell05** [comment]
Jumping right on this :) does this happen for all projects or just paticular ones ?

**Comment by piv199** [comment]
@jcampbell05 `xcake init` and then `xcake make`

**Comment by jcampbell05** [comment]
@albyok how did you fix the first one do you have a patch for that ?

**Comment by jcampbell05** [comment]
Pushed 0.8.12 which should fix the first bug let me know if this fixes it for you

**Comment by albyok** [comment]
The first bug is actually fixed, but I still get the second one :(

**Comment by jcampbell05** [comment]
Okay, do you have a project file I can look into @albyok  It seems like it could be project dependent so a sample will help me a great deal :)

**Comment by albyok** [comment]
It's not easy because I'm talking about work projects. I can't share it so easily. And sorry for my ignorance, but how can it be project dependent if it's your script that should make a whole new file project? :-|

Maybe I can (or you can give me) print some debug messages that can help you find out the problem?

**Comment by jcampbell05** [comment]
Project dependent as in it's something about that project which is triggering a bug in my tool. Yeah thats sounds like a good compromise :)  

or maybe we can chat through a private channel as I'm trying to find which file or folder causes this issue.

**Comment by albyok** [comment]
Sure. If you have Skype, add my job contact: alberto.schiariti_madeinbit

**Comment by albyok** [comment]
News?

**Comment by jcampbell05** [comment]
I think I've traced it down to some bundle files, just running some tests

**Comment by albyok** [comment]
(I think you're ignoring also *.xcdatamodeld files)

**Comment by jcampbell05** [comment]
Good point I'll add those and see if that helps. Will see if there is a full list of bundle files somewhere online

**Comment by albyok** [comment]
Ok. Let me know when the update is coming :D

**Comment by jcampbell05** [comment]
@albyok Okay, I have a few more questions. Does your project have localization ?

**Comment by albyok** [comment]
Yeah.

I'm sorry dude, but I can't rely on this repos anymore. It's like 2 months that I can't use it and I have to find a different solution. 

As I already said, I know that you're not being paid for this (I would pay for this repos if it would work) but I was planning to use it for my job. And 2 months of waiting it's something I can't afford.

I hope that you'll fix it, but I have to look for something else.

**Comment by yonaskolb** [comment]
For what it’s worth https://github.com/yonaskolb/XcodeGen might work out for you

**Comment by albyok** [comment]
@yonaskolb: Thanks. I'll give it a try

**Comment by jcampbell05** [comment]
Okay no worries, I understand. Right now I'm still trying to track it, I can see from your project there is something that it doesn't like which I haven't been able to re-create.

https://github.com/yonaskolb/XcodeGen is a great alternative, as I am considering deprecating this tool as I realised I no longer have the time I once had.
